### ISSUE TITLE
Exclusion of all irrelevant Excel files in a model folder

### ISSUE THREAD

**Issue by BakytzhanSuleimenov** [etsap-TIMES/times-excel-reader#121]
I have tried to run the tool for the JRC-EU-TIMES model and there were also other Excel files for data sources in the model folder and they also went for processing. Maybe will be good to add some prefiltering of Excel files in the folder so the tool takes only relevant files to processing similar to Veda. Exemplar file name filters: VT_*, SubRes*, SysSettings*, BY_Trans*, Scen_*, Trade*, DEM*

**Comment by siddharth-krishna** [comment]
Thanks for raising this issue.

In the meantime, the tool already supports being passed a list of excel files instead of a directory:
```bash
times-excel-reader file1.xslx path/to/file2.xslx file3.xlsx
# instead of:
times-excel-reader path/to/model/
```
Does this perhaps solve your use case already?

**Comment by BakytzhanSuleimenov** [comment]
Thanks @siddharth-krishna,

For now, I am trying to work with cleaned up folder as the list might be long. But the tool is struggling with some files and went into trouble with some files, namely it reports that it has run out of memory. I will try to produce some report on which files it has problems with and try to explore this.

**Comment by olejandro** [comment]
@BakytzhanSuleimenov great that you are trying the tool on another model. It may be a little bit early to do so on JRC EU-TIMES though. I suspect that model includes a lot of cases that this tool is not yet able to handle.

**Comment by BakytzhanSuleimenov** [comment]
Hi @olejandro, this is just an attempt to test the tool and understand it. And as such JRC-EU-TIMES might be a good start to push it to the boundaries. For now, I have discovered that if an Excel file sheet exists with all rows (1048576) initiated (case for some files of JRC-TIMES) even though mostly empty then the tool can complain about not having enough memory. 
However, I don't know what causes a file to have all rows and how it can be handled in the tool.
For example, it is the file with the name "SUBRES_30_TECHS_HeatingCooling_Trans.xlsx" sheet="RSD_HeatCAPEX" from the JRC-EU-TIMES model.

**Comment by olejandro** [comment]
Great! How much RAM did the machine have?

**Comment by BakytzhanSuleimenov** [comment]
I have 16 Gb of RAM, and around 13 Gb free before running the tool, which then takes all free space in RAM
