### ISSUE TITLE
Normalising units

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/times-excel-reader#126]
Currently `PJa`, `pja`, etc are treated as different units by the tool. GAMS on the other hand is case insensitive. Should the tool normalise the units to upper / lowercase?

**Comment by olejandro** [comment]
@Antti-L what do you think?

**Comment by Antti-L** [comment]
Well, if you want to avoid GAMS errors, you should handle all labels without any case sensitivity:
```
  25  SET UNITS /
  26  'PJA'
  27  'Pja'
****      $172
  28  /;
172  Element is redefined
```
I also think this is a reasonable convention anyway, when using the Latin / Latin-1 alphabet.
