### ISSUE TITLE
Don't distinguish between ~TFM_INS and ~FI_T in the mapping file

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/times-excel-reader#57]
Currently we specify whether the output should be generated from a ~TFM_INS or ~FI_T. However some attributes may be present in both table types. At the same time specifying both table types for the same attribute would lead to one of the outputs being overwritten, as per #52

**Comment by siddharth-krishna** [comment]
Aha, interesting. How about the following syntax and semantics for the `times_mapping.txt` file?
```
OutTable[OutCol1, OutCol2, ...] = TABLE[Tag](InCol1, InCol2, ...)
```
This is for the "normal" tables where the output is specified by some columns from the merged input table tagged `Tag`, and we don't filter by an attribute. And
```
OutTable[OutCol1, OutCol2, ...] = TABLE[Tag1, Tag2, ...](InCol1, InCol2, ..., Attribute:AttrName)
```
for the case we're dealing with, where we need to look at more than one tag type and filter all rows where the attribute is `AttrName`.

So for example, we would fix #60 by using the mapping:
```
COM_IE[REG,DATAYEAR,COM,ALL_TS,VALUE] = TABLE[~FI_T,~TFM_INS](Region,Year,CommName,TimeSlice,Attribute:COM_IE)
```

**Comment by siddharth-krishna** [comment]
IIRC, we discussed this on a call and decided that we don't need to change the syntax of the mapping file. Instead, we could create one big merged table called `MainData` or something that includes all the data from both `~FI_T` and `~TFM_INS` tables (and perhaps some others?). We then use this table in the mapping file.

One issue this brings up is the processing of `Other_Indexes`. This should be processed (i.e. exploded into the appropriate columns) before a table is merged into `MainData`.

**Comment by siddharth-krishna** [comment]
I took a look into merging `~FI_T` and `~TFM_INS` into a single `MainData` table before we produce the times tables. However, it looks like they don't have the same columns. `FI_T` has these additional columns:
`Comm-IN, Comm-IN-A, Comm-OUT, Comm-OUT-A, CommName, TechName, Year2, index`
and `TFM_INS` has these additional columns:
`AllRegions, CSet_CD, CSet_CN, CSet_Set, CommGrp, PSet_CI, PSet_CO, PSet_PD, PSet_PN, PSet_Set, SOW, Stage`

Is this just a question of mapping the `TFM_INS` names to the `FI_T` names, e.g. `CSet_CN -> CommName`? Or is there some existing transform that does this to `FI_T` tables that we should also apply to `TFM_INS` tables?

**Comment by olejandro** [comment]
Interesting! I believe we do not need to merge `~FI_T` and `~TFM_INS` at the moment, because it looks like the info from `~TFM_INS` is being added to `~FI_T` already. I.e. in #69 no `~TFM_INS` are left in the mappings file, but the number of correct records doesn't go down.

**Comment by siddharth-krishna** [comment]
Ah interesting. Okay let's close this issue for now and reopen if we find the need to merge them again.
