### ISSUE TITLE
BookRegions underused for determining default Region(s) in VT file tables

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/times-excel-reader#76]
`BookRegions` is used to specify a mapping between a VT workbook name and regional data it contains (i.e. one VT may contain data for several regions). This information should be used to fill out `Region` column default value in VT workbooks. At the moment, we seem to be filling out `Region` column default value with all regions found in `BookRegions` (instead of limiting it to VT specific value(s)).

**Comment by siddharth-krishna** [comment]
I can take a look at this today. Does the following make sense?
Modify `transforms.fill_in_missing_values` to extract the mapping of book name to region first, and then when processing each table, look at the source file name (thanks for adding this!) and if it is of the form `VT_{BookName}_*` then use the mapping to fill in the Region column with the appropriate region.

**Comment by olejandro** [comment]
Sounds good! 👍🏻
