### ISSUE TITLE
Normalize column names and attributes

### ISSUE THREAD

**Issue by siddharth-krishna** [etsap-TIMES/times-excel-reader#81]
Uppercase everything. Also region names. 
Camel case is nice for readability in Excel files and code, so keep it like that, but normalize before comparing.

**Comment by olejandro** [comment]
#87 introduced stripping of leading and trailing spaces in column headers

**Comment by olejandro** [comment]
@siddharth-krishna with #135 merged, can we close this one?

**Comment by siddharth-krishna** [comment]
Column names are done I guess. But do we normalize attribute names already?

**Comment by olejandro** [comment]
We have `capitalise_attributes` that uppercases them.

**Comment by siddharth-krishna** [comment]
Ah yes, thanks, okay let's close this one.
