### ISSUE TITLE
Support additional filtering in the mapping file?

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/times-excel-reader#85]
Currently some of the parameters require custom tags in order to be exported correctly, although filtering could be sufficient.
For example, `PRC_VINT[REG,PRC] = ~FI_Process(Region,TechName)` should either be substituted by preprocessing and a custom tag or could be transformed to something like `PRC_VINT[REG,PRC] = ~FI_Process(Region,TechName,Vintage:YES)`, but the latter would require allowing the mismatch between the number of columns in the mapping.

**Comment by olejandro** [comment]
What do you think @siddharth-krishna ?

**Comment by siddharth-krishna** [comment]
Perhaps we can try to implement the filter syntax first and see if that is sufficient? It's a more general operation so hopefully it applies elsewhere too.

**Comment by olejandro** [comment]
Do you mean expanding the existing syntax (e.g. `Attribute:ACT_COST`) somehow?

**Comment by siddharth-krishna** [comment]
Yes. Perhaps we should start thinking of a more general structure for this mapping file so that we can specify general operations like filter?

**Comment by olejandro** [comment]
We definitely can start thinking about it. :-) Do you think allowing fewer columns on the right is doable already (e.g. `PRC_VINT[REG,PRC] = ~FI_Process(Region,TechName,Vintage:YES)` or `PRC_VINT[REG,PRC] = ~FI_Process(Region,TechName,Vintage)`)?
