### ISSUE TITLE
Number of additional rows is not determined correctly

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/times-excel-reader#86]
We seem to be missing a case when a file is generated that is not present in the "ground truth". I.e. we do not count those rows as additional rows. `PRC_VINT` in e.g. Demo 4 is a good example...

**Comment by siddharth-krishna** [comment]
Ah nice catch. I can fix this next week

**Comment by siddharth-krishna** [comment]
While fixing this, I noticed that we are generating a lot of output tables with no rows in them (e.g. `COM_AGG` in Demo 4-all), and the corresponding files (e.g.  `COM_AGG_output.csv`).
```
WARNING: 43 additional tables: CAP_BND (0), COM_AGG (0), COM_BNDNET (0), COM_CSTNET (0), COM_ELAST (0), COM_GMAP (0), COM_LIM (0), COM_PKTS (0), COM_STEP (0), COM_TAXNET (0), COM_VOC (0), D (5), FLO_COST (0), FLO_DELIV (0), FLO_FR (0), FLO_FUNC (0), FLO_FUNCX (0), FLO_MARK (0), FLO_SHAR (0), FLO_SUB (0), FLO_TAX (0), G_CUREX (0), M (5), NCAP_AF (0), NCAP_AFC (0), NCAP_AFCS (0), NCAP_CHPR (0), NCAP_CPX (0), NCAP_DISC (0), NCAP_DRATE (0), NCAP_ELIFE (0), NCAP_ILED (0), NCAP_PASTI (0), PASTYEAR (1), PRC_ACTFLO (0), PRC_NOFF (0), PRC_VINT (41), SHAPE (0), STGIN_BND (0), STG_EFF (0), STG_LOSS (0), VDA_CEH (0), VDA_FLOP (0)
```
Should we filter out empty tables when we dump tables to files?

**Comment by olejandro** [comment]
Let's keep (some of) the empty tables for now. Those `output` tables that are generated should not be empty, should they? I.e. if they are empty then something is wrong, is it not? On the other hand, if we are generating empty `_additional` and `_missing` output tables, those should be filtered out, I think...

**Comment by siddharth-krishna** [comment]
Which empty tables do you want to keep?

Perhaps I wasn't clear: we are generating a lot of empty additional tables, like `CAP_BND` in Demo 4-all. We're also generating the corresponding files `CAP_BND_output.csv` (these files have just one line, a header). Note that the ground truth files do not have `CAP_BND`. I propose we add a check to `write_csv_tables` to only create files for the non-empty DataFrames.

We aren't generating `_additional` or `_missing` files for things like `CAP_BND` above because `CAP_BND` does not exist in the ground truth.

**Comment by olejandro** [comment]
I see. The empty tables are generated because the tool attempts to generate CSVs for all the attributes in the mapping file, right? Maybe we should consider running it only for the attributes that are actually present in `FI_T`? I guess, this way neither the warning nor the empty files will be generated? I don't think we should change the behaviour for the other tags in the mapping.

Regarding `_additional`  and `_missing`, currently both files are generated even if there are either only missing or only additional records. E.g. in Demo 12:
- `ACT_CUM` only has additional records, so ACT_CUM_missing is empty
- `COM` only has missing records, so COM_additional is empty

**Comment by siddharth-krishna** [comment]
Sounds good, thanks, I can make both these changes.
