### ISSUE TITLE
Output DD files

### ISSUE THREAD

**Issue by siddharth-krishna** [etsap-TIMES/times-excel-reader#94]
Add a feature to output DD files, that can be compared directly to the DD files in https://github.com/olejandro/demos-dd.

@olejandro could you provide some details on the order of tables in the output DD files, and which ones go in which file? Thanks

**Comment by siddharth-krishna** [comment]
I started work on this, and have a few questions:

Do rows within a set need to be sorted alphabetically? I think that's how they appear in the `demos-dd` repo:

![Image](https://github.com/etsap-TIMES/times-excel-reader/assets/10712637/ab24cfe7-252b-41ab-9ebe-c12efe063304)

Why is the last column in this set not quoted? How do we know which columns should be strings, and which not?

![Image](https://github.com/etsap-TIMES/times-excel-reader/assets/10712637/06dff618-a71e-47e0-8822-0d9b41ce3c40)

And to confirm, is it always the `TEXT` column that is used as a comment / [explanatory text](https://www.gams.com/latest/docs/UG_GAMSPrograms.html#UG_GAMSPrograms_Text)?

![Image](https://github.com/etsap-TIMES/times-excel-reader/assets/10712637/6be89120-d92c-413d-8a3a-e8b6cc5466a5)


Btw, it looks like GAMS has an `$ondelim` command that accepts input as CSV files:
https://www.gams.com/latest/docs/UG_DataExchange_ASCII.html

**Comment by olejandro** [comment]
Great, thanks @siddharth-krishna! Sorry, for being slow on providing input!
- no need to sort alphabetically
- keep them all quoted for now. I can check GAMS rules for this, but generally all TIMES internal names should be ok unquoted.
- On `TEXT`, I'd say so.
- On `$ondelim`, ok

To test the accuracy of generated files, one would need to read them with GAMS, do you need help with it?

**Comment by olejandro** [comment]
@siddharth-krishna I guess we can close this one now that #95 is merged?
