### ISSUE TITLE
Using the tool to support diffing TIMES model inputs

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/times-excel-reader#96]
A member of the TIMES community got me thinking about a potentially very useful application of the tool. The tool already generates `raw_tables.txt`. It also can read a subset of a TIMES model files. I guess we could use this to pin point differences between 2 model versions? I.e. currently when comparing model versions we only know which files are different, but the output of the tool can allows us seeing the changes in model input.

What do you think @siddharth-krishna ?

**Comment by siddharth-krishna** [comment]
Sorry, I lost this notification somehow. Great idea! Users can diff `raw_tables.txt`, or we could also provide a `--diff` flag and then use https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.compare.html to produce a more succinct output.

Alternatively, once we have #95 users could compare the resulting GDX files using `gdxdiff`?

**Comment by olejandro** [comment]
Yes, users seem to be diffing `raw_tables.txt` already. 😄 I am thinking maybe in the future we could potentially run the tool for each excel file that has differences?

**Comment by siddharth-krishna** [comment]
This is great. Maybe we can add a section to the readme giving examples/instructions on how to use the tool this way?
