### ISSUE TITLE
Generate MILESTONYR

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/times-excel-reader#97]
> * Add the value of `MILESTONYR` to `benchmarks.yml` for each Demo. How do I obtain the correct values for each Demo?

The actual MILESTONYR sets used in each Demo run can be obtained from the corresponding RUN file (usually produced by VEDA). But the full set is easy to obtain, as you are writing out the parameters B(year) and E(year). In other words, the full set of valid MILESTONYR in each run case of the Demo models consists of those years, for which B and E are defined (I assume these are according to the `~ActivePDef` in SysSettings?). That set of years, defined by the **Active Period Definition**, may only be changed in the actual run by "truncation" (i.e. the run horizon can be made **shorter** by dropping a few last years out).  So, unless you can pick the MILESTONYR definition from the RUN file, I think you should be fine by defining MILESTONYR as that full set of the years in the Active Period Definition.

_Originally posted by @Antti-L in https://github.com/etsap-TIMES/times-excel-reader/issues/95#issuecomment-1658347678_

**Comment by Antti-L** [comment]
**Comment**:  The above comment I posted earlier is related to the "legacy" period definition method used in the Demo models.  In that method it is required that the Milestone year T of any period is always `FLOOR( (B(T)+E(T))/2 )`.  Therefore, as the parameters B and E seem to be already defined correctly according to the Active Period Definition for the Milestone years T, it should be trivial to define the full `SET MILESTONYR` consistently with those B(T) and E(T) values.  Nonetheless, for more complete support, I think the user should be able to specify the name of the desired **PDef** (one of those defined in SysSettings) and the Ending year TLAST (last milestone to be included) for a run case, and then the Excel reader would define B and E using **that** period definition, and the `SET MILESTONYR` would be generated as a subset of the full set, inluding only those `T ≤ TLAST`. 

However, as Olex has pointed out elsewhere, there is also another way of defining the periods:  By directly specifying the Milestone years.  But as this alternative method has not been used in the test models, I guess you can postone handling it.

**Comment by olejandro** [comment]
Thanks @Antti-L !
@siddharth-krishna , actually we already calculate milestone years, we just don't export them. I.e. see `process_time_periods` and the `M` column. I guess, @samwebster was working on this part?
Adding `MILESTONYR[VALUE] = ~TimePeriods(M)` to the mapping file should generate them. However, I guess, the regression testing would fail, unless we also update the benchmarks...
